#!/bin/bash

# shellcheck disable=SC2034
COMMAND=$1
ARGUMENT=$2

declare -A commands

commands[--start]="docker compose --env-file .env.local up $ARGUMENT"
commands[--restart]="docker compose --env-file .env.local restart"
commands[--stop]="docker compose --env-file .env.local stop"
commands[--connect]="docker compose --env-file .env.local exec -it \"$ARGUMENT\" /bin/bash"
commands[--build]="docker compose --env-file .env.install up --build $ARGUMENT"
commands[--kill]="killContainers"
commands[--remove]="removeContainers"

function runCommand() {
    ${commands[$COMMAND]}
}

function killContainers() {
    for container in ${ARGUMENT[@]}; do
        docker kill "$container"
    done
}

function removeContainers() {
    for container in ${ARGUMENT[@]}; do
        docker rm "$container"
    done
}

# Викликаємо runCommand, щоб виконати команду
runCommand

