#!/bin/bash

# shellcheck disable=SC2034
COMMAND=$1
ARGUMENT=$2

if [[ $COMMAND == "--start" ]]; then
    docker compose --env-file .env.local up $ARGUMENT
fi
if [[ $COMMAND == "--restart" ]]; then
    docker compose --env-file .env.local restart
fi
if [[ $COMMAND == "--stop" ]]; then
    docker compose --env-file .env.local stop
fi
if [[ $COMMAND == "--connect" ]]; then
    docker compose --env-file .env.local exec -it "$ARGUMENT" /bin/bash
fi
if [[ $COMMAND == "--build" ]]; then
    docker compose --env-file .env.install up --build $ARGUMENT
fi
if [[ $COMMAND == "--kill" ]]; then
    for container in ${ARGUMENT[@]}; do
    docker kill $container
    done
fi
if [[ $COMMAND == "--remove" ]]; then
    for container in ${ARGUMENT[@]}; do
    docker remove $container
    done
fi
